# -*- coding: utf-8 -*-
"""Perhitungan Chi-Square Test.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ts8-TRCM43C7lm4t2HDmOBP_ZtoHJ5_X
"""

import numpy as np

# Data observasi
observed = np.array([
    [80, 65, 42, 36],  # Kota
    [47, 52, 95, 12]   # Desa
])

# Hitung total baris dan kolom
row_totals = observed.sum(axis=1)
col_totals = observed.sum(axis=0)
total = observed.sum()

# Hitung nilai expected
expected = np.outer(row_totals, col_totals) / total

# Hitung Chi-square
chi_square = np.sum((observed - expected) ** 2 / expected)

# Print hasil
print("Nilai Chi-Square:", chi_square)
print("Nilai expected:")
print(expected)

# Hasil: Nilai Chi-Square ≈ 64.76